# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1403744225);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1403744345);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1403741918);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1403741798);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 15);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 6);
user_pref("browser.search.defaultenginename", "Yahoo");
user_pref("browser.search.order.1", "Yahoo");
user_pref("browser.search.order.2", "Ixquick");
user_pref("browser.search.order.3", "Startpage");
user_pref("browser.search.order.4", "DuckDuckGo");
user_pref("browser.search.selectedEngine", "Yahoo");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140410211157");
user_pref("browser.showQuitWarning", true);
user_pref("browser.slowStartup.averageTime", 6627);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage", "http://www.linuxmint.com/start/qiana");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1403484544731");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1403716541874");
user_pref("datareporting.policy.firstRunTime", "1403398144730");
user_pref("datareporting.sessions.current.activeTicks", 5);
user_pref("datareporting.sessions.current.firstPaint", 5198);
user_pref("datareporting.sessions.current.main", 1145);
user_pref("datareporting.sessions.current.sessionRestored", 5763);
user_pref("datareporting.sessions.current.startTime", "1403802322639");
user_pref("datareporting.sessions.current.totalTime", 33);
user_pref("datareporting.sessions.currentIndex", 6);
user_pref("datareporting.sessions.previous.0", "{\"s\":1403398136045,\"a\":59,\"t\":1254,\"c\":false,\"m\":1790,\"fp\":17382,\"sr\":17068}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1403477028526,\"a\":25,\"t\":2547,\"c\":false,\"m\":1061,\"fp\":7719,\"sr\":8277}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1403568891707,\"a\":15,\"t\":3159,\"c\":false,\"m\":4774,\"fp\":12158,\"sr\":12821}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1403649411884,\"a\":46,\"t\":23802,\"c\":false,\"m\":1043,\"fp\":5822,\"sr\":5459}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1403684532033,\"a\":75,\"t\":1441,\"c\":false,\"m\":1046,\"fp\":5581,\"sr\":7025}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1403716475211,\"a\":86,\"t\":18490,\"c\":false,\"m\":1081,\"fp\":4955,\"sr\":5834}");
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 6);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"28.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"28.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "mint-search-enhancer%40linuxmint.com:1.0,%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D:1.0.7,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:28.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140319.01");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1401409783000,\"rdfTime\":1397165557000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1397166426000},\"mint-search-enhancer@linuxmint.com\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/mint-search-enhancer@linuxmint.com\",\"mtime\":1401409913000,\"rdfTime\":1346324837000},\"{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}\",\"mtime\":1401409914000,\"rdfTime\":1336770080000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1397166426000}}}]");
user_pref("extensions.lastAppVersion", "28.0");
user_pref("extensions.lastPlatformVersion", "28.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140410211157");
user_pref("gecko.mstone", "28.0");
user_pref("idle.lastDailyNotification", 1403745161);
user_pref("keyword.URL", "https://duckduckgo.com/?t=lm&q=");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.protocol-handler.app.apt", "/usr/bin/apturl");
user_pref("network.protocol-handler.app.apt+http", "/usr/bin/apturl");
user_pref("network.protocol-handler.warn-external.apt", true);
user_pref("network.protocol-handler.warn-external.apt+http", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1403658761);
user_pref("places.history.expiration.transient_current_max_pages", 52847);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1403658761);
user_pref("toolkit.startup.last_success", 1403802323);
user_pref("toolkit.telemetry.previousBuildID", "20140410211157");
user_pref("urlclassifier.download_allow_table", "");
user_pref("urlclassifier.download_block_table", "");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1405990154);
